"""
ontology_utils.py — Utilities for human-readable labels of Wikidata PIDs,
class QIDs and entity QIDs.

Sources:
  1. ``ontologies/*.json`` — the 10 curated Text2KGBench ontologies, source-
     of-truth for the 90 properties and 128 domain classes. They take
     *precedence* over the Wikidata cache for PIDs/class QIDs present in both.
  2. ``utils/wikidata_labels_cache.json`` — cache auto-generated by
     ``utils.fetch_wikidata_labels`` for PIDs/QIDs not covered by the
     ontologies or not labeled in the subgraph nodes:
       - ``pid_labels``: standard properties such as P21, P19, P31, ...
       - ``class_labels``: non-ontology classes (TYPE edge targets)
       - ``entity_labels``: Wikidata entities that appear in edges but lack a
         label in the subgraph (reached as extra_props targets during expansion)

The merge produces three unified dictionaries ``pid_labels``, ``class_labels``,
``entity_labels`` that cover ~100% of the dataset's identifiers.
"""

import json
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
ONTO_DIR = PROJECT_ROOT / "ontologies"
WIKIDATA_CACHE_PATH = Path(__file__).resolve().parent / "wikidata_labels_cache.json"

# Process-level cache (built once per module load)
_LABELS_CACHE: dict[str, dict[str, str]] | None = None


def load_ontology_labels(ont_dir: Path = ONTO_DIR,
                         wikidata_cache: Path = WIKIDATA_CACHE_PATH
                         ) -> dict[str, dict[str, str]]:
    """
    Load and merge labels from ontologies + Wikidata cache.

    Returns:
        dict with keys ``"pid_labels"``, ``"class_labels"``, ``"entity_labels"``.

    Precedence:
      Ontologies take precedence over the Wikidata cache. If a PID/QID is
      present in both (rare case), the ontology label wins (curated,
      domain-specific). ``entity_labels`` come only from the cache, not from
      the ontologies (by definition the ontologies do not contain individual
      entities).
    """
    global _LABELS_CACHE
    if _LABELS_CACHE is not None:
        return _LABELS_CACHE

    pid_labels: dict[str, str] = {}
    class_labels: dict[str, str] = {}
    entity_labels: dict[str, str] = {}

    # 1. Load the Wikidata cache first (lower priority for pid/class)
    if wikidata_cache.exists():
        try:
            with open(wikidata_cache, encoding="utf-8") as fh:
                cache = json.load(fh)
            pid_labels.update(cache.get("pid_labels", {}))
            class_labels.update(cache.get("class_labels", {}))
            entity_labels.update(cache.get("entity_labels", {}))
        except Exception:
            # Corrupted or unreadable cache: ignore silently
            pass

    # 2. Load the ontologies (higher priority — overwrites cached pid/class)
    for f in sorted(Path(ont_dir).glob("*.json")):
        with open(f, encoding="utf-8") as fh:
            o = json.load(fh)
        for c in o.get("concepts", []):
            qid = c.get("qid")
            label = (c.get("label") or "").strip()
            if qid and label:
                class_labels[qid] = label
        for r in o.get("relations", []):
            pid = r.get("pid")
            label = (r.get("label") or "").strip()
            if pid and label:
                pid_labels[pid] = label

    _LABELS_CACHE = {
        "pid_labels": pid_labels,
        "class_labels": class_labels,
        "entity_labels": entity_labels,
    }
    return _LABELS_CACHE


def count_ontologies_with_qid(qid: str, ont_dir: Path = ONTO_DIR) -> int:
    """How many of the 10 ontologies list ``qid`` among their concepts."""
    count = 0
    for f in Path(ont_dir).glob("*.json"):
        with open(f, encoding="utf-8") as fh:
            ont = json.load(fh)
        if any(c["qid"] == qid for c in ont["concepts"]):
            count += 1
    return count


if __name__ == "__main__":
    # Manual smoke test: not executed when the module is imported elsewhere.
    labels = load_ontology_labels()
    print(f"Property labels loaded: {len(labels['pid_labels'])}")
    print(f"Class    labels loaded: {len(labels['class_labels'])}")
    print(f"\nProperty examples:")
    for pid in ("P161", "P57", "P175", "P50")[:4]:
        print(f"  {pid} -> {labels['pid_labels'].get(pid, '(not found)')}")
    print(f"\nClass examples:")
    for qid in ("Q11424", "Q5", "Q482994"):
        print(f"  {qid} -> {labels['class_labels'].get(qid, '(not found)')}")
    n = count_ontologies_with_qid("Q5")
    print(f"\nOntologies containing Q5 (human): {n}")
